### ISSUE TITLE
Task List - Lab #1

### ISSUE THREAD

**Issue by apurbaanik** [apurbaanik/HelloWorld#2]
Task List:
- [x] Create a repository
- [x] Add HelloWorld.java
- [x] Create a README file with a description.
- [x] Do the bonus part.
- [ ] Submit the link in MS Teams.

Bonus: 
- [x] Task List in the Issues. 
- [x] Use the issue tracker on GitHub repo.

**Comment by apurbaanik** [comment]
Added the source code for HelloWorld.java.

**Comment by apurbaanik** [comment]
Updated comments in my source code
